---
branches:
  only:
  - master

language: java

jdk:
  - openjdk11

os: linux

arch:
  - s390x
  - ppc64le

script:
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-s390x && export PATH=$JAVA_HOME/bin:$PATH;
  - chmod u+x ./sbt
